name: Client

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: CI Pipeline Here 
        run: 'true'
